import {
  EnterpriseWorkflow,
  WorkflowPriority,
  WorkflowRiskLevel,
  WorkflowStatus,
} from '../models/enterprise-workflow.models';

export const ENTERPRISE_WORKFLOW_FIXTURES: ReadonlyArray<EnterpriseWorkflow> = [
  {
    id: 'wf-001',
    name: 'SkillEvolve Angular scoring dashboard',
    repository: 'SkillEvolve/skillevolve-frontend',
    status: WorkflowStatus.IN_REVIEW,
    priority: WorkflowPriority.URGENT,
    owner: {
      id: 'u-001',
      fullName: 'Nour Ghouila',
      email: 'nourghouila57@gmail.com',
      role: 'developer',
      capacityPerWeek: 22,
    },
    reviewers: [
      {
        id: 'u-002',
        fullName: 'Tech Lead Angular',
        email: 'lead@example.com',
        role: 'tech-lead',
        capacityPerWeek: 10,
      },
    ],
    tasks: [
      {
        id: 'task-001',
        title: 'Add reactive workflow wizard',
        description: 'Create a typed FormArray based wizard for quality criteria.',
        column: 'done',
        priority: WorkflowPriority.HIGH,
        estimate: 8,
        spent: 7,
        assigneeId: 'u-001',
        dueDate: '2026-06-16',
        tags: ['forms', 'angular'],
        dependencies: [],
        acceptanceCriteria: ['Typed forms', 'Validation messages', 'Draft save'],
      },
      {
        id: 'task-002',
        title: 'Connect workflow API',
        description: 'Integrate HttpClient with search, update, patch and delete endpoints.',
        column: 'review',
        priority: WorkflowPriority.URGENT,
        estimate: 6,
        spent: 5,
        assigneeId: 'u-001',
        dueDate: '2026-06-17',
        tags: ['backend', 'rxjs'],
        dependencies: ['task-001'],
        acceptanceCriteria: ['HttpParams', 'HttpHeaders', 'Error handling'],
      },
    ],
    findings: [
      {
        id: 'finding-001',
        criterion: 'maintainability',
        severity: WorkflowRiskLevel.LOW,
        message: 'Most logic is isolated in utility functions.',
        recommendation: 'Keep shared scoring rules pure and tested.',
        resolved: true,
        scoreImpact: 0.05,
      },
      {
        id: 'finding-002',
        criterion: 'rxjs',
        severity: WorkflowRiskLevel.MEDIUM,
        message: 'Some streams require explicit loading state.',
        recommendation: 'Use scan and finalize to keep state consistent.',
        resolved: false,
        scoreImpact: 0.12,
      },
    ],
    createdAt: '2026-06-10T08:00:00.000Z',
    updatedAt: '2026-06-15T08:00:00.000Z',
    tags: ['angular', 'quality', 'enterprise'],
    metadata: {
      sprint: 4,
      criticalForDemo: true,
      framework: 'angular',
    },
  },
];
